export const AVAILABLE_COLORS = [
  "Noir",
  "Blanc",
  "Gris",
  "Rouge",
  "Bleu",
  "Vert",
  "Jaune",
  "Orange",
  "Rose",
  "Violet",
  "Marron",
  "Beige",
  "Multicolore",
  "Or",
  "Argent",
];

export const AVAILABLE_SIZES = [
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "36",
  "38",
  "40",
  "42",
  "44",
  "46",
  "48",
  "Unique",
];

export const COLOR_MAP: Record<string, string> = {
  Noir: "#000000",
  Blanc: "#FFFFFF",
  Gris: "#808080",
  Rouge: "#EF4444",
  Bleu: "#3B82F6",
  Vert: "#22C55E",
  Jaune: "#EAB308",
  Orange: "#F97316",
  Rose: "#EC4899",
  Violet: "#8B5CF6",
  Marron: "#78350F",
  Beige: "#F5F5DC",
  Multicolore:
    "linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet)",
  Or: "#FFD700",
  Argent: "#C0C0C0",
};
